### ISSUE TITLE
VC natvis bug for eastl::string

### ISSUE THREAD

**Issue by ivalylo** [electronicarts/EASTL#173]
Hi, the VC natvis file seems to be a bit old. Here is a fix for the string

```
<Type Name="eastl::basic_string&lt;char,*&gt;">
	<DisplayString>{mPair.mFirst.heap.mpBegin,s}</DisplayString>
	<Expand>
		<Item Name="length"   Condition="!!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">mPair.mFirst.heap.mnSize</Item>
		<Item Name="capacity" Condition="!!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">(mPair.mFirst.heap.mnCapacity
		&amp; ~kHeapMask)</Item>
		<Item Name="value"    Condition="!!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">mPair.mFirst.heap.mpBegin,sb</Item>

		<Item Name="length"   Condition="!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">mPair.mFirst.sso.mSizeField.mnSize</Item>
		<Item Name="capacity" Condition="!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">SSOLayout::SSO_CAPACITY</Item>
		<Item Name="value"    Condition="!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">mPair.mFirst.sso.mData,sb</Item>

		<Item Name="uses heap">!!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)</Item>
	</Expand>
</Type>

<Type Name="eastl::basic_string&lt;wchar_t,*&gt;">
	<DisplayString>{mPair.mFirst.heap.mpBegin,su}</DisplayString>
	<Expand>
		<Item Name="length"   Condition="!!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">mPair.mFirst.heap.mnSize</Item>
		<Item Name="capacity" Condition="!!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">(mPair.mFirst.heap.mnCapacity
		&amp; ~kHeapMask)</Item>
		<Item Name="value"    Condition="!!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">mPair.mFirst.heap.mpBegin,sb</Item>

		<Item Name="length"   Condition="!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">mPair.mFirst.sso.mSizeField.mnSize</Item>
		<Item Name="capacity" Condition="!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">SSOLayout::SSO_CAPACITY</Item>
		<Item Name="value"    Condition="!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">mPair.mFirst.sso.mData,sb</Item>

		<Item Name="uses heap">!!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)</Item>
	</Expand>
</Type>
```

**Comment by ivalylo** [comment]
Here is better version with proper condition for DisplayString

```
<Type Name="eastl::basic_string&lt;char,*&gt;">
	<DisplayString Condition="!!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">{mPair.mFirst.heap.mpBegin,s}</DisplayString>
    <DisplayString Condition="!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">{mPair.mFirst.sso.mData,s}</DisplayString>
	<Expand>
		<Item Name="length"   Condition="!!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">mPair.mFirst.heap.mnSize</Item>
		<Item Name="capacity" Condition="!!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">(mPair.mFirst.heap.mnCapacity &amp; ~kHeapMask)</Item>
		<Item Name="value"    Condition="!!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">mPair.mFirst.heap.mpBegin,sb</Item>

		<Item Name="length"   Condition="!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">mPair.mFirst.sso.mSizeField.mnSize</Item>
		<Item Name="capacity" Condition="!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">SSOLayout::SSO_CAPACITY</Item>
		<Item Name="value"    Condition="!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">mPair.mFirst.sso.mData,sb</Item>

		<Item Name="uses heap">!!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)</Item>
	</Expand>
</Type>

<Type Name="eastl::basic_string&lt;wchar_t,*&gt;">
    <DisplayString Condition="!!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">{mPair.mFirst.heap.mpBegin,su}</DisplayString>
    <DisplayString Condition="!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">{mPair.mFirst.sso.mData,su}</DisplayString>
	<Expand>
		<Item Name="length"   Condition="!!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">mPair.mFirst.heap.mnSize</Item>
		<Item Name="capacity" Condition="!!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">(mPair.mFirst.heap.mnCapacity &amp; ~kHeapMask)</Item>
		<Item Name="value"    Condition="!!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">mPair.mFirst.heap.mpBegin,sb</Item>

		<Item Name="length"   Condition="!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">mPair.mFirst.sso.mSizeField.mnSize</Item>
		<Item Name="capacity" Condition="!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">SSOLayout::SSO_CAPACITY</Item>
		<Item Name="value"    Condition="!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)">mPair.mFirst.sso.mData,sb</Item>

		<Item Name="uses heap">!!(mPair.mFirst.sso.mSizeField.mnSize &amp; kSSOMask)</Item>
	</Expand>
</Type>
```

**Comment by rparolin** [comment]
Should be fixed in the latest release.

**Comment by JohanEffektfabriken** [comment]
Hello,
It looks like this still isn't fully fixed. The problem is the **sb** format-specifier given for DisplayString and Value. It indicates const char* string (no quotation marks) according to:
[https://docs.microsoft.com/en-us/visualstudio/debugger/format-specifiers-in-cpp?view=vs-2017](url)

Using the current implementation only the first letter is showing up when using wstrings. Probably wrong for _char8_t_, _char16_t_ and _char32_t_ as well, but haven't tested so not sure.

Making two sections with type destinction; char, and wchar_t, using **sb** format-specifier for the first and **su** for the second seams to work.

```xml
<Type Name="eastl::basic_string&lt;char,*&gt;">
    <DisplayString Condition="!!(mPair.mFirst.sso.mRemainingSizeField.mnRemainingSize &amp; kSSOMask)">"{mPair.mFirst.heap.mpBegin,sb}"</DisplayString>
    <DisplayString Condition="!(mPair.mFirst.sso.mRemainingSizeField.mnRemainingSize &amp; kSSOMask)">"{mPair.mFirst.sso.mData,sb}"</DisplayString>
    <Expand>
        <Item Name="[length]"   Condition="!!(mPair.mFirst.sso.mRemainingSizeField.mnRemainingSize &amp; kSSOMask)">mPair.mFirst.heap.mnSize</Item>
        <Item Name="[capacity]" Condition="!!(mPair.mFirst.sso.mRemainingSizeField.mnRemainingSize &amp; kSSOMask)">(mPair.mFirst.heap.mnCapacity &amp; ~kHeapMask)</Item>
        <Item Name="[value]"    Condition="!!(mPair.mFirst.sso.mRemainingSizeField.mnRemainingSize &amp; kSSOMask)">mPair.mFirst.heap.mpBegin,sb</Item>

        <Item Name="[length]"   Condition="!(mPair.mFirst.sso.mRemainingSizeField.mnRemainingSize &amp; kSSOMask)">mPair.mFirst.sso.mRemainingSizeField.mnRemainingSize</Item>
        <Item Name="[capacity]" Condition="!(mPair.mFirst.sso.mRemainingSizeField.mnRemainingSize &amp; kSSOMask)">SSOLayout::SSO_CAPACITY</Item>
        <Item Name="[value]"    Condition="!(mPair.mFirst.sso.mRemainingSizeField.mnRemainingSize &amp; kSSOMask)">mPair.mFirst.sso.mData,sb</Item>

        <Item Name="[uses heap]">!!(mPair.mFirst.sso.mRemainingSizeField.mnRemainingSize &amp; kSSOMask)</Item>
    </Expand>
</Type>

<Type Name="eastl::basic_string&lt;wchar_t,*&gt;">
    <DisplayString Condition="!!(mPair.mFirst.sso.mRemainingSizeField.mnRemainingSize &amp; kSSOMask)">"{mPair.mFirst.heap.mpBegin,su}"</DisplayString>
    <DisplayString Condition="!(mPair.mFirst.sso.mRemainingSizeField.mnRemainingSize &amp; kSSOMask)">"{mPair.mFirst.sso.mData,su}"</DisplayString>
    <Expand>
        <Item Name="[length]"   Condition="!!(mPair.mFirst.sso.mRemainingSizeField.mnRemainingSize &amp; kSSOMask)">mPair.mFirst.heap.mnSize</Item>
        <Item Name="[capacity]" Condition="!!(mPair.mFirst.sso.mRemainingSizeField.mnRemainingSize &amp; kSSOMask)">(mPair.mFirst.heap.mnCapacity &amp; ~kHeapMask)</Item>
        <Item Name="[value]"    Condition="!!(mPair.mFirst.sso.mRemainingSizeField.mnRemainingSize &amp; kSSOMask)">mPair.mFirst.heap.mpBegin,su</Item>

        <Item Name="[length]"   Condition="!(mPair.mFirst.sso.mRemainingSizeField.mnRemainingSize &amp; kSSOMask)">mPair.mFirst.sso.mRemainingSizeField.mnRemainingSize</Item>
        <Item Name="[capacity]" Condition="!(mPair.mFirst.sso.mRemainingSizeField.mnRemainingSize &amp; kSSOMask)">SSOLayout::SSO_CAPACITY</Item>
        <Item Name="[value]"    Condition="!(mPair.mFirst.sso.mRemainingSizeField.mnRemainingSize &amp; kSSOMask)">mPair.mFirst.sso.mData,su</Item>

        <Item Name="[uses heap]">!!(mPair.mFirst.sso.mRemainingSizeField.mnRemainingSize &amp; kSSOMask)</Item>
    </Expand>
</Type>
```
