### ISSUE TITLE
Unable to sort non-copy-constructible objects

### ISSUE THREAD

**Issue by sekmet64** [electronicarts/EASTL#92]
The code below fails to compile with eastl but works fine with libc++
```
std::vector<std::unique_ptr<int>> vec;
eastl::sort(vec.begin(), vec.end());
```

**Comment by rparolin** [comment]
Thanks for submitting this.  I take a look at it.

**Comment by rparolin** [comment]
Is this an std/eastl interop bug?  Or are you saying eastl::vector<eastl::unique_ptr>>  fails to compile when passd to the eastl::sort?

**Comment by sekmet64** [comment]
No sorry for being too vague, it's the lack of support for only move-constructible objects in the sorting algorithms. The same error can be reproduced on both msvc and clang with:

```
eastl::vector<eastl::unique_ptr<int>> vec;
eastl::sort(vec.begin(), vec.end(),  [](const eastl::unique_ptr<int>& lhs, const eastl::unique_ptr<int>& rhs) { return *lhs < *rhs; });
```

**Comment by theryee** [comment]
Been experimenting with this one. Fix for this looks fairly involved as I believe it involves changing sort.h's move support.

**Comment by rparolin** [comment]
Yes, it is an involved change.  I have this work tracked in our internal backlog but so I will get around to doing it at some point in the future.

**Comment by theryee** [comment]
I think I got this figured out... just need to fix some build issues for some of the compilers.

**Comment by theryee** [comment]
I've posted an updated review.

**Comment by rparolin** [comment]
Sound be resolved with release 3.05.06.

**Comment by theryee** [comment]
I think this is still an issue? I tried applying only the most basic test here:
https://github.com/theryee/EASTL/commit/7623f1023718330129a3604c570a39752d3c5291

But still see compile errors regarding attempting to use the deleted copy constructor for unique_ptr:
https://travis-ci.org/theryee/EASTL/builds/239803490?utm_source=github_status&utm_medium=notification

**Comment by theryee** [comment]
Note: my PR is still open and un-merged... did you implement a fix independently?
